# Guided Project: Analyzing Thanksgiving Dinner
Use the pandas package to analyze what Americans eat for Thanksgiving dinner.

### Introducing Thanksgiving Dinner Data
    Instructions
- Read the thanksgiving.csv file in.
- Display the first few rows of data to see what the columns and rows look like.
- Display all of the column names to get a sense of what the data consists of.

In [3]:
import pandas as pd

In [9]:
data = pd.read_csv("/home/aida/Desktop/Dataquest/Step 2/data-analysis-with-pandas/data/thanksgiving-2015-poll-data.csv", encoding = "Latin-1")
data.head()
# data.columns

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific

### Filtering Out Rows From A DataFrame

    Instructions
- Display counts of how many times each category occurs in the Do you celebrate Thanksgiving? column.
- Filter out any rows in data where the response to Do you celebrate Thanksgiving? is not Yes.

In [100]:
celebrate = data["Do you celebrate Thanksgiving?"]
#pd.Series.value_counts(celebrate)
celebrate.value_counts()

Yes    980
No      78
Name: Do you celebrate Thanksgiving?, dtype: int64

In [101]:
data = data[celebrate.values == "Yes"]

### Using value_counts To Explore Main Dishes
    Instructions
- Display counts of how many times each category occurs in the What is typically the main dish at your Thanksgiving dinner? column.
- Display the Do you typically have gravy? column for any rows from data where the What is typically the main dish at your Thanksgiving dinner? column equals Tofurkey.
- Create a filter that only selects rows from data where What is typically the main dish at your Thanksgiving dinner? equals Tofurkey.

In [102]:
main_dish = data["What is typically the main dish at your Thanksgiving dinner?"]
main_dish.value_counts()

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

In [103]:
data["Do you typically have gravy?"][main_dish == "Tofurkey"]

4      Yes
33     Yes
69      No
72      No
77     Yes
145    Yes
175    Yes
218     No
243    Yes
275     No
393    Yes
399    Yes
571    Yes
594    Yes
628     No
774     No
820     No
837    Yes
860     No
953    Yes
Name: Do you typically have gravy?, dtype: object

In [104]:
# Create a filter that only selects rows from data where What is typically the main dish at your Thanksgiving dinner? equals Tofurkey.
data[main_dish == "Tofurkey"]

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific
33,4337771439,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Suburban,30 - 44,Male,"$50,000 to $74,999",Middle Atlantic
69,4337553422,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,Yes,No,No,NaN,Urban,18 - 29,Male,"$10,000 to $24,999",West South Central
72,4337540484,Yes,Tofurkey,NaN,I don't know,NaN,Bread-based,NaN,None,NaN,...,No,No,Yes,No,NaN,Suburban,18 - 29,Male,Prefer not to answer,Pacific
77,4337490067,Yes,Tofurkey,NaN,Roasted,NaN,None,NaN,None,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,Prefer not to answer,East North Central
145,4337191550,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,No,No,No,NaN,Urban,30 - 44,Female,"$125,000 to $149,999",West South Central
175,4337139327,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,No,No,NaN,Rural,30 - 44,Female,"$75,000 to $99,999",West North Central
218,4337078951,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,Yes,No,No,NaN,Suburban,30 - 44,Female,"$200,000 and up",Mountain
243,4337044348,Yes,Tofurkey,NaN,Other (please specify),various ways,Bread-based,NaN,Canned,NaN,...,No,No,No,No,NaN,Urban,60+,Female,"$100,000 to $124,999",South Atlantic
275,4336997445,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,No,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Middle Atlantic
393,4336894719,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,Canned,NaN,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$25,000 to $49,999",New England
399,4336891075,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Suburban,60+,Female,"$125,000 to $149,999",South Atlantic
571,4336760110,Yes,Tofurkey,NaN,Roasted,NaN,Bread-based,NaN,None,NaN,...,No,No,No,No,NaN,Suburban,18 - 29,Female,Prefer not to answer,South Atlantic
594,4336736562,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,No,No,No,No,NaN,Rural,45 - 59,Female,"$175,000 to $199,999",Middle Atlantic
628,4336692873,Yes,Tofurkey,NaN,Baked,NaN,None,NaN,Homemade,NaN,...,No,No,Yes,No,NaN,Suburban,60+,Female,"$25,000 to $49,999",Middle Atlantic
774,4336400854,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,No,Yes,No,Yes,Yes,Suburban,45 - 59,Female,"$75,000 to $99,999",Mountain
820,4336238126,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,No,No,No,No,NaN,Urban,18 - 29,Female,"$10,000 to $24,999",Pacific
837,4336175740,Yes,Tofurkey,NaN,Baked,NaN,None,NaN,None,NaN,...,No,No,Yes,Yes,No,Suburban,18 - 29,Female,"$25,000 to $49,999",West North Central
860,4336121663,Yes,Tofurkey,NaN,Baked,NaN,Rice-based,NaN,Other (please specify),freshly made at a deli counter,...,No,Yes,No,No,NaN,Urban,30 - 44,Female,"$25,000 to $49,999",Pacific
953,4336005220,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Suburban,30 - 44,Male,"$0 to $9,999",Middle Atlantic

### Figuring Out What Pies People Eat
    Instructions  
- We can find out how many people eat one of these three pies for Thanksgiving dinner by figuring out for how many people all three columns are null.

In [105]:
apple = data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple"]
pumpkin = data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin"]
pecan = data["Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan"]
apple_isnull = apple.isnull()
pumpkin_isnull = pumpkin.isnull()
pecan_isnull = pecan.isnull()
no_pies = apple_isnull & pumpkin_isnull & pecan_isnull
no_pies.value_counts()

False    876
True     104
dtype: int64

In [106]:
# Where that Series contains False, the person ate at least one of the types of pies for Thanksgiving dinner. Where it contains True, they ate none of the types of pies.
ate_pie = pd.isnull(apple) & pd.isnull(pumpkin) & pd.isnull(pecan)
ate_pie.value_counts()

False    876
True     104
dtype: int64

###  Converting Age To Numeric
    Instructions
- Write a function to convert a single string to an appropriate integer value. This will allow us to convert the values in the Age column to integers.

In [107]:
age = data["Age"]
age.value_counts()

45 - 59    269
60+        258
30 - 44    235
18 - 29    185
Name: Age, dtype: int64

In [108]:
def string_to_int(age_string):
    if pd.isnull(age_string):
        return None
    age_string = age_string.split(" ")[0]
    age_string = age_string.replace("+", "")
    return int(age_string)

data["int_age"] = age.apply(string_to_int)
data["int_age"].describe()

count    947.000000
mean      40.089757
std       15.352014
min       18.000000
25%       30.000000
50%       45.000000
75%       60.000000
max       60.000000
Name: int_age, dtype: float64

### Converting Income To Numeric
- The How much total combined money did all members of your HOUSEHOLD earn last year? column is very similar to the Age column. It contains categories, but can be converted to numerical values.

In [109]:
income = data["How much total combined money did all members of your HOUSEHOLD earn last year?"]
income.value_counts()

$25,000 to $49,999      166
$50,000 to $74,999      127
$75,000 to $99,999      127
Prefer not to answer    118
$100,000 to $124,999    109
$200,000 and up          76
$10,000 to $24,999       60
$0 to $9,999             52
$125,000 to $149,999     48
$150,000 to $174,999     38
$175,000 to $199,999     26
Name: How much total combined money did all members of your HOUSEHOLD earn last year?, dtype: int64

In [110]:
def extract_string(str_income):
    if pd.isnull(str_income):
        return None
    str_income = str_income.split(" ")[0]
    if str_income == "Prefer":
        return None
    str_income = str_income.replace("$", "")
    str_income = str_income.replace(",", "")
    return int(str_income)

data["int_income"] = income.apply(extract_string)   
data["int_income"].describe()

count       829.000000
mean      75965.018094
std       59068.636748
min           0.000000
25%       25000.000000
50%       75000.000000
75%      100000.000000
max      200000.000000
Name: int_income, dtype: float64

### Correlating Travel Distance And Income
- See how far people earning under 150000 will travel.
- See how far people earning over 150000 will travel.

In [111]:
data[data["int_income"] < 150000]["How far will you travel for Thanksgiving?"].value_counts()

Thanksgiving is happening at my home--I won't travel at all                         281
Thanksgiving is local--it will take place in the town I live in                     203
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    150
Thanksgiving is out of town and far away--I have to drive several hours or fly       55
Name: How far will you travel for Thanksgiving?, dtype: int64

In [112]:
data[data["int_income"] > 150000]["How far will you travel for Thanksgiving?"].value_counts()

Thanksgiving is happening at my home--I won't travel at all                         49
Thanksgiving is local--it will take place in the town I live in                     25
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    16
Thanksgiving is out of town and far away--I have to drive several hours or fly      12
Name: How far will you travel for Thanksgiving?, dtype: int64

### Linking Friendship And Age
- Generate a pivot table showing the average age of respondents for each category of Have you ever tried to meet up with hometown friends on Thanksgiving night? and Have you ever attended a "Friendsgiving?".
- Generate a pivot table showing the average income of respondents for each category of Have you ever tried to meet up with hometown friends on Thanksgiving night? and Have you ever attended a "Friendsgiving?".

In [117]:
data.pivot_table(values = "int_age",
                 index = "Have you ever tried to meet up with hometown friends on Thanksgiving night?",
                 columns="Have you ever attended a \"Friendsgiving?\"")

Have you ever attended a "Friendsgiving?"                  No        Yes
Have you ever tried to meet up with hometown fr...
No                                                  42.283702  37.010526
Yes                                                 41.475410  33.976744

In [118]:
data.pivot_table(values = "int_income",
                columns = "Have you ever attended a \"Friendsgiving?\"",
                index = "Have you ever tried to meet up with hometown friends on Thanksgiving night?")

Have you ever attended a "Friendsgiving?"                     No           Yes
Have you ever tried to meet up with hometown fr...
No                                                  78914.549654  72894.736842
Yes                                                 78750.000000  66019.736842

## __Here are some potential next steps:__

    Figure out the most common dessert people eat.
    Figure out the most common complete meal people eat.
    Identify how many people work on Thanksgiving.
    Find regional patterns in the dinner menus.
    Find age, gender, and income based patterns in dinner menus.